### ISSUE TITLE
Wrong font type is loading in specific icons sets

### ISSUE THREAD

**Issue by ilukanets** [material-icons/material-icons-font#1]
Hello. I've just started used Material icons and I need only Outlined icons set. However there is an error in outlined.css file (and other sets as well). When I'm loading outlined.css font file is still related to Baseline font family.
Please see my screenshot https://prnt.sc/rmhocr

**Comment by cyberalien** [comment]
Thanks for reporting!

Fixed.

**Comment by ilukanets** [comment]
@cyberalien Thanks a lot for a quick reaction. I really appreciate this and your work around these cool icons. 
I have one more question for you... 
Are there some plans to push these repository and make it available as npm package? I believe this could be really useful for me and other users. 
Thanks.

**Comment by cyberalien** [comment]
Sure, I'll do that.

**Comment by ilukanets** [comment]
Thanks.
Looking forward for this.

**Comment by cyberalien** [comment]
Done.

Package name is `@material-icons/font`

**Comment by ilukanets** [comment]
Great... Thanks a lot!!
