### ISSUE TITLE
Define variables as "!default"

### ISSUE THREAD

**Issue by jmatthiesen81** [material-icons/material-icons-font#4]
It would be awesome if you declare the variables as `!default` to make them configurable.

E.g. https://github.com/material-icons/material-icons-font/blob/master/scss/all.scss#L3

From:
```scss
$font-path: '../font/';
```

To:
```scss
$font-path: '../font/' !default;
```

Thanks for the nice package. Kind regards. :heart:

**Comment by cyberalien** [comment]
Sure, that makes total sense. I'll update it.

**Comment by cyberalien** [comment]
Done.

**Comment by jmatthiesen81** [comment]
Nice, thanks for the very fast reaction. :rocket:  :heart:
